version: '3'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data/bd/MongoDB:/data/db

  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
    ports:
      - 3309:3306
    volumes:
      - ./data/bd/MySQL:/var/lib/mysql

  mariadb:
    image: mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbpassword
    ports:
      - 3307:3306
    volumes:
      - ./data/bd/MariaDB:/var/lib/mysql

  my_express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    environment:
      - MONGODB_HOST=mongodb

      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysqlpassword

      - MARIADB_HOST=mariadb
      - MARIADB_USER=root
      - MARIADB_PASSWORD=mariadbpassword

      - DOCKER_SERVER_PORT_EXPOSED=5000
    depends_on:
      - mongodb
      - mysql
      - mariadb
    volumes:
      - ./server:/servidor
      - /servidor/node_modules
